name: {{ cookiecutter.stage_name }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
    - '{{ cookiecutter.stage_folder_name }}/**'
  workflow_dispatch: # enable manual execution

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      FOLDER_NAME: {{ cookiecutter.stage_folder_name }}
      CONDA_ENV_NAME: {{ cookiecutter.stage_environment_name }}
      CONDA_ENV_FILE: {{ cookiecutter.stage_folder_name }}/environment.yml
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ '{{' }} github.token {{ '}}' }}

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        activate-environment: ${{ '{{' }} env.CONDA_ENV_NAME {{ '}}' }}
        auto-activate-base: false
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

    - name: Cache conda
      uses: actions/cache@v2
      id: conda_cache_id
      env:
        # increase this value to reset cache even if environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: /usr/share/miniconda/envs/${{ '{{' }} env.CONDA_ENV_NAME {{ '}}' }}
        key: ${{ '{{' }} env.CONDA_ENV_NAME {{ '}}' }}-${{ '{{' }} runner.os {{ '}}' }}-conda-${{ '{{' }} env.CACHE_NUMBER {{ '}}' }}-${{ '{{' }} hashFiles(env.CONDA_ENV_FILE) {{ '}}' }}

    - name: Conda env update
      # only needed when dependencies has been changed
      if: steps.conda_cache_id.outputs.cache-hit != 'true'
      run: |
        conda env update --file $CONDA_ENV_FILE

    - name: Conda info
      run: |
        conda info
        conda env list
        conda env export

    - name: Run {{ cookiecutter.stage_name }}
      env:
        {{ cookiecutter.stage_env_var_prefix }}INPUT_FILE: "path/to/file.ext"
        {{ cookiecutter.stage_env_var_prefix }}OUTPUT_DIR: "path/to/output/dir"
      run: |
        ./$FOLDER_NAME/run.sh

    - name: Upload run output artifact
      run: |
        echo "TODO: upload artifact..."
      # uses: actions/upload-artifact@v2
      # with:
      #   name: {{ cookiecutter.stage_folder_name }}_output-run_${{ '{{' }} github.run_number {{ '}}' }}-id_${{ '{{' }} github.run_id {{ '}}' }}
      #   path: |
      #     ${{ '{{' }} env.FOLDER_NAME {{ '}}' }}/out/
      #     !${{ '{{' }} env.FOLDER_NAME {{ '}}' }}/out/.gitkeep
      #   if-no-files-found: error
