name: CI Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # enable manual execution

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Cookiecutter
      run: pip install cookiecutter

    - name: Generate stage
      run: cookiecutter . --no-input --verbose stage_name="Generated Stage"

    - name: Upload generated stage
      uses: actions/upload-artifact@v2
      with:
        name: generated_stage
        path: generated_stage/
        if-no-files-found: error
